apiVersion: apps/v1
kind: Deployment
metadata:
  name: ring
spec:
  selector:
    matchLabels:
      app: ring
  replicas: 1
  template:
    metadata:
      labels:
        app: ring
    spec:
      containers:
      - name: ring
        image: okteto.dev/ring:latest
        ports:
        - containerPort: 8080
        
---
    
apiVersion: v1
kind: Service
metadata:
  name: ring
spec:
  type: LoadBalancer 
  ports:
    - name: http
      port: 8080
  selector:
    app: ring
